# Generated by Django 5.0.6 on 2024-06-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='user_image/default-profile.png', null=True, upload_to='user_image/'),
        ),
    ]
